# Generated by Django 5.0.2 on 2025-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='department',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
